### ISSUE TITLE
0.7.0 TODO list

### ISSUE THREAD

**Issue by d3cod3** [d3cod3/Mosaic#80]
- [x] Drag and drop objects to subpatch on subpatches list to move them https://github.com/d3cod3/ofxVisualProgramming/commit/bab017b0324d5da5bf98467a4bca0b2560068951
- [x] Save canvas displacement position in patch, to always restore last view https://github.com/d3cod3/ofxVisualProgramming/commit/61dee99a7f4bc55c53bd21de53fa1a5e17c2a524
- [x] ~~Study this: https://github.com/onurae/core-nodes and check availability to switch canvas code from OF to ImGui ( removing ofxInfiniteCanvas addon )~~ **Leave it for 0.7.1 release**
- [x] ~~Add needed sound objects ( quantizer, sample&hold, parametric eq )~~ **Leave it for 0.7.1 release**
- [x] ~~Add external panning control for mixer object~~ **Leave it for 0.7.1 release**
- [x] Add multi-slider object with variable number of sliders ( vertical ) https://github.com/d3cod3/ofxVisualProgramming/commit/0710e574139fed6cd01515f52396377406818731
- [x] Add multi toggle object with variable number of toggles https://github.com/d3cod3/ofxVisualProgramming/commit/2cdb27806e5297e2419ae890396632082a33abe0
- [x] Modify number object, include internal trigger to on/off data flow ( from internal menu ) https://github.com/d3cod3/ofxVisualProgramming/commit/ee4076a415e5b5e43356ab7e172a83fd473e9a92
- [x] Modify number and slider object, to set and save variable name, for usability https://github.com/d3cod3/ofxVisualProgramming/commit/805b0784ee736971f29bad52ebf6bf9eb849cb66
- [x] Implement [scheme scripting language from OF](https://github.com/d3cod3/ofxScheme)
- [x]  ~~add scheme script object with live coding on output window~~ **Leave it for 0.7.1 release**
- [x] ~~Change actual logger to a debug terminal: [ImTerm](https://github.com/Organic-Code/ImTerm)~~ Modify actual logger for passing commands, add selectable text and copy/paste https://github.com/d3cod3/Mosaic/commit/39853cb4acd67c2c4a889cdbd217c18904069d1f
- [x] Add some simple visual programming patches examples

**Comment by d3cod3** [comment]
![Screenshot from 2024-11-30 23-13-20](https://github.com/user-attachments/assets/b5eb1119-08b0-4c3f-b865-fd3ee24a6037)

https://github.com/d3cod3/ofxVisualProgramming/commit/bab017b0324d5da5bf98467a4bca0b2560068951

**Comment by d3cod3** [comment]
![Screenshot from 2024-11-30 23-14-29](https://github.com/user-attachments/assets/344899dc-0ab2-474f-aaa7-9199a2ba2b0b)

https://github.com/d3cod3/ofxVisualProgramming/commit/805b0784ee736971f29bad52ebf6bf9eb849cb66

**Comment by d3cod3** [comment]
![Screenshot from 2024-11-30 23-32-46](https://github.com/user-attachments/assets/94dbd5a2-04d8-4b0a-8db4-9dc1a4951bde)

https://github.com/d3cod3/ofxVisualProgramming/commit/ee4076a415e5b5e43356ab7e172a83fd473e9a92

**Comment by d3cod3** [comment]
![mosaicScreenshot_241208](https://github.com/user-attachments/assets/f3801fa0-7196-42d6-ba39-b655a2e35a68)

![Screenshot from 2024-12-08 01-00-14](https://github.com/user-attachments/assets/cb268506-fc7f-4af0-9260-a80f38b01238)

https://github.com/d3cod3/Mosaic/commit/39853cb4acd67c2c4a889cdbd217c18904069d1f

**Comment by d3cod3** [comment]
![Screenshot from 2024-12-08 11-38-09](https://github.com/user-attachments/assets/6ea5f502-d40e-4ffe-ba02-8da55e48bf03)

https://github.com/d3cod3/ofxVisualProgramming/commit/0710e574139fed6cd01515f52396377406818731

**Comment by d3cod3** [comment]
![Screenshot from 2024-12-08 17-38-27](https://github.com/user-attachments/assets/3fd4f6ef-d819-4f22-bf58-f0241ae067ef)

https://github.com/d3cod3/ofxVisualProgramming/commit/2cdb27806e5297e2419ae890396632082a33abe0

**Comment by Daandelange** [comment]
In debug builds the chat is broken, in release there's an imgui::TextEditor API violation without crashes.
- `SetReadOnly(true);` --> asserts when a new message is sent, because it's readonly.

**Comment by d3cod3** [comment]
Thanks Daan!

I think this fixes it:

https://github.com/d3cod3/Mosaic/commit/1a37626fa9a79fee2f9d92c5df0c463c26668964

**Comment by d3cod3** [comment]
![Screenshot from 2024-12-12 12-12-21](https://github.com/user-attachments/assets/be25afe1-234b-4f98-b18a-1b5bac17af2d)

![Screenshot from 2024-12-12 12-12-43](https://github.com/user-attachments/assets/364634f6-6a6d-4a04-9738-01e39c0b6ce7)


![Screenshot from 2024-12-12 12-12-53](https://github.com/user-attachments/assets/7426952c-94ee-422b-a16e-9cf905789be4)

https://github.com/d3cod3/ofxScheme

**Comment by Daandelange** [comment]
Core-nodes looks awesome indeed, and the code seems pretty compatible and minimal, while using pugi XML for saving/loading ! :D
As this API is more object-oriented I guess we'll have to inherit our nodes/params/pins from theirs ?

**Comment by d3cod3** [comment]
Yes, at first look it seems like you say, but it's something i want to check with no rush, to choose carefully what to use from there and what maintain from what we have already.
The idea is to have full retro-compatibility with patches made with previous Mosaic releases first, and then integrate all the good code from Core-nodes as much as we can, removing ofxInfiniteCanvas dependecy.
