### ISSUE TITLE
0.7.2 TODO list

### ISSUE THREAD

**Issue by d3cod3** [d3cod3/Mosaic#84]
- [x] Add needed sound objects ( **quantizer**, **parametric eq** )
- [x] Add **address sequencer** object
- [x] Manage canvas drag/zoom with imgui ( reference from https://github.com/onurae/core-nodes/ )
- [x] Add canvas interaction from imgui ( select nodes for group drag, duplicate, delete )
- [x] Add **piano keyboard** object, to visualize MIDI notes from external devices and/or play notes ( outputs pitch )
- [x] Update **midi receiver** object to receive multiple midi message simultanously ( for chords, etc.., now only receive the last midi message )
- [x] Add **polyphonic oscillator** object
- [x] Add external panning control for mixer object
- [x] Add **scheme live coding** object with live coding on output window
- [x] Fix duplicate filepath in objects with loaded file when duplicate, now only duplicates object with no file 
- [x] Add commands to the new logger/console

**Comment by d3cod3** [comment]
![Screenshot from 2025-01-01 19-09-57](https://github.com/user-attachments/assets/f678f3cc-2471-4f93-a6f1-00967763ad71)

![Screenshot from 2025-01-01 19-09-49](https://github.com/user-attachments/assets/fb556783-cc4b-47e0-8aaa-d012a49933e0)

![Screenshot from 2025-01-01 19-10-16](https://github.com/user-attachments/assets/92524abc-5c53-4039-a63b-c2bb7aac48cb)

https://github.com/d3cod3/ofxVisualProgramming/commit/c2897641dd506daf7f9a4ee9cffa962e1d84cfbb

https://github.com/d3cod3/Mosaic/commit/75436ac80780b31cce4c3127eb441f4e735d45f1

Patch canvas drag&zoom now managed from imgui:

- right click, reset zoom to standard
- right click with drag, drag the canvas
- mouse scroll, zoom in/out the canvas
- click on node header, drag the node

**Comment by d3cod3** [comment]
![Screenshot from 2025-01-03 11-23-06](https://github.com/user-attachments/assets/eb77721e-b434-4a4b-a4ba-fd1b23977488)


![Screenshot from 2025-01-04 19-39-44](https://github.com/user-attachments/assets/db93d0aa-22f5-490b-b098-6756d8342c48)

![Screenshot from 2025-01-04 19-40-26](https://github.com/user-attachments/assets/fe5aa762-9c3b-427b-9579-a202cf61d383)

![Screenshot from 2025-01-04 19-41-05](https://github.com/user-attachments/assets/991db3a7-5d13-4ac6-a8ae-dbb972deabef)




https://github.com/d3cod3/ofxVisualProgramming/commit/b991ea3e33f790dc7d97c09935ecdaff96e85926

Added patch canvas interaction with imgui:

- drag mouse --> select nodes
- click on canvas --> deselect nodes
- click and drag over selected nodes --> move nodes
- BACKSPACE_KEY --> delete selected nodes/delete selected links
- MOD_KEY-D --> duplicate selected nodes
- CTRL-click links -> select links
- click on canvas --> deselect links
- SHIFT-click links --> deactivate/activate links

**Comment by d3cod3** [comment]
Fix duplicate filepath in objects with loaded file when duplicate

https://github.com/d3cod3/ofxVisualProgramming/commit/07f92053ace7d90fbf8cf549fab9e4a348e4fe21

**Comment by d3cod3** [comment]
![Screenshot from 2025-01-06 12-42-02](https://github.com/user-attachments/assets/1c25d1dc-32c7-434e-9de1-1716fe8d2712)

Added **piano keyboard** object, to visualize MIDI notes from external devices and/or play notes with mouse ( outputs pitch )

https://github.com/d3cod3/ofxVisualProgramming/commit/e70ba3982bfec33f340776996b4d8421145f23d6

**Comment by d3cod3** [comment]
![Screenshot from 2025-01-08 19-00-38](https://github.com/user-attachments/assets/4bee27ad-5798-461f-8d78-4b4b6d7204d1)

![Screenshot from 2025-01-08 19-02-21](https://github.com/user-attachments/assets/d709709e-5c19-4ffe-8930-be59dd9428a4)

![Screenshot from 2025-01-08 19-02-35](https://github.com/user-attachments/assets/3642a97c-e6f4-4080-bf95-ba8248be7395)

![Screenshot from 2025-01-08 19-02-53](https://github.com/user-attachments/assets/27ab5d89-e4df-4cc6-91e8-49e000260d67)

Added scheme script object with live coding on output window

https://github.com/d3cod3/ofxVisualProgramming/commit/e3c674b8d4e4d59e1fc7dc353ebb9c2911eb858e

**Comment by d3cod3** [comment]
![mosaicScreenshot_250113](https://github.com/user-attachments/assets/526ae9c4-1120-47ab-a56e-85e9d441796b)

Added polyphonic oscillator, up to 16 voices

https://github.com/d3cod3/ofxVisualProgramming/commit/a54b34786443977909775b0ac47e9b9c44b371e5

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/c29a8e2f-471b-48f8-a537-7fd5ff98a2bf)

![Image](https://github.com/user-attachments/assets/5622650e-a615-4b76-9db6-1d38b47335d5)

updated midi receiver to receive multiple simultanously midi messages, for piano keyboard and polyphonic oscillator objects

https://github.com/d3cod3/ofxVisualProgramming/commit/8a65c9a0e5d8d3c817aa7f9e7a891f0f54d23a8a

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/7d6dc8d5-fc76-49bf-920d-cbbc3ec67017)

Added parametric equalizer object

https://github.com/d3cod3/ofxVisualProgramming/commit/8f62e76c4613c0ba92fcd39996ec0e35af0b7a7a

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/8329a1e4-dcc8-4fa0-ab26-053a578d1f73)

Added quantizer object

https://github.com/d3cod3/ofxVisualProgramming/commit/81aed6f341be9f59fbf0343f3577f2983a83d5cd

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/44b38910-7c66-477a-b98e-13545d844d53)

![Image](https://github.com/user-attachments/assets/62ef853c-9356-4495-9500-3c5c72698e8b)

Added 8 step address sequencer object

https://github.com/d3cod3/ofxVisualProgramming/commit/ad627c354486e9ba54dd866b04b34fc1a3d83c7a

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/37a35b5c-9256-40f9-9af2-2a018d2885df)

Added a minimal set of console commands

**Comment by d3cod3** [comment]
![Image](https://github.com/user-attachments/assets/979c1755-46d2-46fb-8d5f-7e630987c6dc)

Added **summing mixer** object, last one for 0.7.2, finished developing 0.7.2, now testing it...
